### ISSUE TITLE
can your give me some help?

### ISSUE THREAD

**Issue by gechangwei** [thuehn/RegMon#10]
hi:
    Your tool is very well, give me lots of help. But i have a problem about the value of  "channel_time_busy  channel_time_rx  channel_time_tx"; What is real means abot this three value. I think "channel_time_rx + channel_time_tx <= channel_time_busy". Can you help me easy understand these values?

  Thank you very much.

**Comment by thuehn** [comment]
Hi,

The maening of those values after you have applyed the parsing script (parse_default_RegMon-trace.awk) is described in the README as:

    ktime = kernel time stamp
    d_tx = absolute tx busy state count difference in ticks from previous sample
    d_rx = absolute rx busy state count difference in ticks from previous sample
    d_idle = absolute idle state count difference in ticks from previous sample
    d_others = absolute (energy_detection - rx_busy) state count difference in ticks from previous sample

Within the parse_default_RegMon-trace.awk you can look up how the the calculation is done.

If you look at the raw register values, than the meaning is:
register_2 = MAC clock ticks
register_3 = tx_busy state in clock ticks (only transmit busy)
register_4 = rx_busy state in clock ticks (only receiving busy)
register_5 = energy_detection state in clock ticks (all busy states from tx, rx, noise)

Greetings Thomas

**Comment by gechangwei** [comment]
hi：
    Thank you very much for your reply. I also have a problem if in the channel two STA's packet collision, this value will be in "rx_busy state in clock ticks" or "energy_detection state in clock ticks" ?
    Thank you again.

**Comment by gechangwei** [comment]
This means is in a AP and have two STA, can i get the collision value from your tool ?
In my opinion "energy_detection state in clock ticks" -  "rx_busy state in clock ticks" -  "tx_busy state in clock ticks" = noise + collision . Is this right?

**Comment by thuehn** [comment]
Hi Gechangwei,

rx_busy states sum the clock ticks where the mac state machine of the Atheros card are trying to demodulate frames, regardless if the demodulation succeeds or not. The energy_detection states sum the clock ticks where the mac state machine senses the channel busy by not yet demodulate, so to say the carrier sensing state is active. 
In your case, if you are interessted in analysing a packet collision szenario, I would first of all set the samling rate of regmon to something about 20kHz, to allow a distingction bettween single packets. If you have a packet collision from two packets coming from two STAs each, there are potentially more than szenarios what the PHY of the AP could do ... depending on the collision timing the Phy of the ap could start with sensing the first packet, start demodulating it and resense to the second packet and start demodulating it ... or stop demudolation because of ohy errors .. ect.
You probably need to have a proper measurement setup to perform thos packet collsion sending szenarios in such a manner that you can repeat them with the same timings and look at the RegMon and pcap monitor captures.

Greetings from Berlin
Thomas

**Comment by gechangwei** [comment]
Hi Thomas:
    I am very thanks for your reply and I probably understand what you mean. But i also a little can't understand. 
    You say "**************(1) depending on the collision timing the Phy of the ap could start with sensing the first packet, start demodulating it and resense to the second packet and start demodulating it ... (2) or stop demudolation because of ohy errors .. ect **************"   I can't very clear the (1).  I think in the  (2) "or stop demudolation because of ohy errors" means the rx_busy is not to work , just the channel busy  is this right ? what is meaning of "ohy" and "szenario"?
    Thank you very much .  

CQUPT from China
Grant    Gechangwei

**Comment by thuehn** [comment]
Hi Gechangwei,

Lets assume one AP and two STAs, where STA(1) starts to trasmit a packet at time T0 with duration(D1) and STA(2) starts to transmit its packet at time T1=T0+delay with duration(D2) towards the AP. The delay is smaller than the packet airtime so the packet transmission overlep. Now you monitor/sample the mac layer states at 20kHz at the AP with the help of RegMon. 
As both packet will overlep it could be that (1) the AP can not demodulate any packet, (2) the AP senses the packet from STA(2) and can demodulate it and (3) the AP properly demodulate packet from STA(1). Which of the 3 szenarios happen, depends on several factors.. most signifcant the SNR of the packets and the receiver sensivity. But ether way, I would expect that the mac layer states recored by RegMon should count up rx busy states for the duration of: T1+D2-T0. You will measure certain energy detection states for the first packet and if the second packet is sensed (case (3) ) again energy detection states. Maybe you can provide a short description of your measurement setup and also a RegMon plot for the traffice you have set up ?

Greetings from Berlin
Thomas

**Comment by gechangwei** [comment]
Hi Thomas :
    Thank you for your reply . I probably understand what you mean. I took a long time and did some measurements at the same time. Getting a precise collision time is a very difficult thing. But i want use the "(TX_BUSY+RX_BUSY) / CHANNEL_active_time(this the mac state time)" beacause if packets collision the STAs must restart backoff, so the channel must be idle . So i want use this way make a sample measurement for  may be call "Time utilization". This way need more analysis if i want accurate .Do you feel that this method works? I want get your opinion .

    Thanks again.

CQUPT from China
Grant Gechangwei

**Comment by thuehn** [comment]
Hi Gechnagwei,

I think your approach sounds resonable to start witch. Lets have a look at your data to decide what you might want to change.

Greetings from Berlin
Thomas

**Comment by gechangwei** [comment]
hi Thomas ,
    I can't understand why "channel_busy_time > channel_rx_time + channel_tx_time", just has noice or something. May you give me some help?
    Thanks again.later I will give my test for you.

**Comment by thuehn** [comment]
Hi Gechangwei,

I thought that you have checked the awk source code from the RegMon parser to get those insides. Anyway, let my clarify this, as it is importent for you to understand those relations:

register_2 = MAC clock ticks
register_3 = tx_busy state in clock ticks (only transmit busy)
register_4 = rx_busy state in clock ticks (only receiving busy)
register_5 = energy_detection state in clock ticks (all busy states from tx, rx, noise)

So to transfer this to your formula:
CHANNEL_BUSY_TIME (register_5) = TX_BUSY (register_3)+ RX_BUSY (register_4) + NOISE/ENERGY-DETECTION_BUSY

NOISE/ENERGY-DETECTION_BUSY = CHANNEL_BUSY_TIME (register_5) -  TX_BUSY (register_3) - RX_BUSY (register_4)

CHANNEL_IDLE = MAC_BUSY (register_2) - CHANNEL_BUSY_TIME (register_5)

NOISE/ENERGY-DETECTION_BUSY are those MAC states, where the Atheros wifi card's carrier sensing unit is busy while detecting packets/energy/noise but the demodulating rx unit is not xet started.

Greetings from Berlin
Thomas

**Comment by gechangwei** [comment]
Hi Thomas :
    Thanks again. I send my test date in your email about "thomas <thomas@net.t-labs.tu-berlin.de>".
    Thanks again.
