### ISSUE TITLE
mac_state_plot example

### ISSUE THREAD

**Issue by thuehn** [thuehn/RegMon#4]
![mac_state_plot](https://cloud.githubusercontent.com/assets/1880886/9112743/c1cca18e-3c50-11e5-8474-e4eabce5b95d.jpg)

**Comment by bittorf** [comment]
describe the steps to generate this GFX

**Comment by thuehn** [comment]
Hi Basti,
I just added the Rscript to plot RegMons default logging output.
So a one-liner to plot is: 
cat register_log | gawk --non-decimal-data -v header=1 -v clock=44 -f parse_default_RegMon-trace.awk | ./plot_MAC-states_from_RegMon.r

An example register_log file is in ./RegMon.
You need to have R installed with the additional packages ggplot and reshape2.

Greetins Thomas

**Comment by thuehn** [comment]
![regmon](https://cloud.githubusercontent.com/assets/1880886/9155283/6ad13628-3eb3-11e5-96b3-f78cbcc6b7c5.png)
