### ISSUE TITLE
U32_MAX >> 2 undeclared

### ISSUE THREAD

**Issue by gechangwei** [thuehn/RegMon#6]
in yong patch file of the 9983 
 if (  cycles > (  U32_MAX  >> 2 )  ) , 
has an error says "  U32_MAX  " undeclared ;
could you tell me ,how can i solve this question？
 thank you

**Comment by gechangwei** [comment]
in yong patch file of the 9983 
if ( cycles > ( U32_MAX >> 2 ) ) , 
has an error says " U32_MAX " undeclared ;
could you tell me ,how can i solve this question？
thank you

**Comment by thuehn** [comment]
Hi,

The U32_MAX is a linux kernel macro which defines the maximum varable range of an u32.
#define U32_MAX         ((u32)~0U)
reference at: http://lxr.free-electrons.com/source/include/linux/kernel.h#L38

Greetings Thomas
